server:
  port: 40017
  servlet:
    context-path: /api/mastercard

spring:
  application:
    name: api-mastercad-service-v1

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration